name: WASM / Qt 6.5.0
on:
  push:
    branches:
      - '*'

jobs:
  buildUbuntuXenial:
    runs-on: ubuntu-18.04
    env:
      CC: emcc
      CXX: em++

    strategy:
      matrix:
        build-type: [Release]

    steps:

    - name: Job info
      run: |
        echo "GitHub Ref: ${{ github.ref }}"
        echo "Event: ${{ github.event }}"

    - name: get container ready for build
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q --force-yes \
        automake cmake git wget libfuse2 desktop-file-utils tree \
        build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev \
        libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 \
        libxcb-xinerama0 libxcb-composite0 libxcb-cursor0 libxcb-damage0 \
        libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 libxcb-ewmh2 libxcb-glx0 \
        libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 \
        libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-util1 libegl1

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ matrix.qt-version }}

    - name: install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest 3.1.25
        ./emsdk activate 3.1.25

    - name: install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'linux'
        target: 'wasm_multithread'
        modules: 'qtcharts'
        install-deps: false
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: checkout sources
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: build Ripes
      run: |
        echo "--------------------------------------------------------------"
        echo "building desktop"
        source emsdk/emsdk_env.sh
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} .
        make -j $(nproc)

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.build-type }}_executable
        path: |
          Ripes.wasm
          Ripes.js
          Ripes.worker.js
          qtloader.js
